INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (1, 'DINAS PENDIDIKAN, KEPEMUDAAN DAN OLAHRAGA');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (2, 'DINAS KESEHATAN');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (3, 'RUMAH SAKIT UMUM DAERAH KOTA KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (4, 'DINAS PEKERJAAN UMUM DAN PENATAAN RUANG');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (5, 'DINAS KEBAKARAN');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (6, 'DINAS PERUMAHAN, KAWASAN PERMUKIMAN DAN PERTANAHAN');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (7, 'BADAN PERENCANAAN PEMBANGUNAN DAERAH');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (8, 'DINAS PERHUBUNGAN');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (9, 'DINAS LINGKUNGAN HIDUP DAN KEHUTANAN');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (11, 'DINAS KEPENDUDUKAN DAN PENCATATAN SIPIL');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (12, 'DINAS PEMBERDAYAAN PEREMPUAN DAN PERLINDUNGAN ANAK');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (13, 'DINAS SOSIAL');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (14, 'BADAN KESATUAN BANGSA DAN POLITIK');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (15, 'SATUAN POLISI PAMONG PRAJA');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (16, 'SEKRETARIAT DPRD');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (18, 'SEKRETARIAT DAERAH');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (20, 'BADAN PENGELOLA PAJAK DAN RETRIBUSI DAERAH');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (21, 'SEKRETARIAT DEWAN PENGURUS KORPRI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (22, 'INSPEKTORAT DAERAH');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (23, 'BADAN PENANAMAN MODAL DAN PELAYANAN TERPADU SATU PINTU');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (24, 'BADAN KEPEGAWAIAN DAN PENGEMBANGAN SUMBER DAYA MANUSIA');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (25, 'KECAMATAN KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (26, 'KECAMATAN MANDONGA');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (27, 'KECAMATAN POASIA');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (28, 'KECAMATAN BARUGA');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (29, 'KECAMATAN KENDARI BARAT');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (30, 'KECAMATAN ABELI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (31, 'KECAMATAN KADIA');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (32, 'KECAMATAN WUA-WUA');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (33, 'KECAMATAN KAMBU');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (34, 'KECAMATAN PUUWATU');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (99, 'BADAN PENGELOLAAN KEUANGAN DAN ASET DAERAH');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (100, 'BADAN PENANGGULANGAN BENCANA DAERAH');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (101, 'DINAS PANGAN');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (103, 'DINAS PERPUSTAKAAN DAN KEARSIPAN');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (104, 'DINAS PERTANIAN');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (106, 'DINAS KEBUDAYAAN DAN PARIWISATA');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (107, 'DINAS KELAUTAN DAN PERIKANAN');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (108, 'DINAS PERDAGANGAN, KOPERASI DAN UMKM');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (109, 'SEKRETARIAT KPU');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (111, 'DINAS PENGENDALIAN PENDUDUK DAN KELUARGA BERENCANA');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (112, 'DINAS KOMUNIKASI DAN INFORMATIKA');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (113, 'DINAS TENAGA KERJA DAN PERINDUSTRIAN');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (114, 'KECAMATAN NAMBO');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (115, 'DINAS PENANAMAN MODAL DAN PELAYANAN TERPADU SATU PINTU');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (116, 'UPTD DIKNAS KECAMATAN KENDARI BARAT');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (117, 'UPTD DIKNAS KECAMATAN KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (118, 'UPTD DIKNAS KECAMATAN KAMBU');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (119, 'UPTD DIKNAS KECAMATAN MANDONGA');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (120, 'UPTD DIKNAS KECAMATAN WUA-WUA');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (121, 'UPTD DIKNAS KECAMATAN POASIA');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (122, 'UPTD DIKNAS KECAMATAN ABELI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (123, 'UPTD DIKNAS KECAMATAN BARUGA');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (124, 'UPTD DIKNAS KECAMATAN KADIA');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (125, 'UPTD DIKNAS KECAMATAN PUUWATU');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (126, 'Puskesmas NAMBO');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (127, 'Puskesmas ABELI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (128, 'Puskesmas POASIA');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (129, 'Puskesmas MOKOAU');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (130, 'Puskesmas JATIRAYA');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (131, 'Puskesmas PERUMNAS');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (132, 'Puskesmas MEKAR');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (133, 'Puskesmas WUA-WUA');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (134, 'Puskesmas LEPO-LEPO');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (135, 'Puskesmas KEMARAYA');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (136, 'Puskesmas BENU-BENUA');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (137, 'Puskesmas KANDAI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (138, 'Puskesmas MATA');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (139, 'Puskesmas PUUWATU');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (140, 'Puskesmas LABIBIA');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (141, 'SMPN 01 KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (142, 'SMPN 02 KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (143, 'SMPN 03 KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (144, 'SMPN 04 KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (145, 'SMPN 05 KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (146, 'SMPN 06 KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (147, 'SMPN 07 KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (148, 'SMPN 08 KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (149, 'SMPN 09 KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (150, 'SMPN 10 KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (151, 'SMPN 11 KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (152, 'SMPN 12 KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (153, 'SMPN 13 KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (154, 'SMPN 14 KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (155, 'SMPN 15 KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (156, 'SMPN 16 KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (157, 'SMPN 17 KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (158, 'SMPN 18 KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (159, 'SMPN 19 KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (160, 'SMPN 20 KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (161, 'SMAN 01 KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (162, 'SMAN 02 KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (163, 'SMAN 03 KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (164, 'SMAN 04 KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (165, 'SMAN 05 KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (166, 'SMAN 06 KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (167, 'SMAN 07 KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (168, 'SMAN 08 KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (169, 'SMAN 09 KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (170, 'SMAN 10 KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (171, 'SMKN 1 KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (172, 'SMKN 2 KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (173, 'SMKN 3 KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (174, 'SMKN 4 KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (175, 'SMKN 5 KENDARI');
INSERT INTO `skpd_tbl` (`kd_skpd`, `nama`) VALUES (176, 'SMKN 6 KENDARI');
